Cargo.toml, Changelog.md, src/_derive_tutorial.rs, src/args.rs, src/info.rs, src/lib.rs, src/meta_help.rs, src/meta_usage.rs, src/meta_youmean.rs, src/params.rs, src/structs.rs, src/tests.rs
Better error messages when using commands and alternatives
Suggestions for typos in code
Fixes #30
=> Improve error handling UX

Cargo.toml, Changelog.md, README.md, src/args.rs, src/info.rs, src/meta_youmean.rs, src/params.rs, src/structs.rs, src/tests.rs
=> More cosmetic stuff

Cargo.toml, Changelog.md, src/info.rs, src/tests.rs
preserve suggestion context when returning from a subcommand
=> and a bit more cosmetics

Cargo.toml, bpaf_cauwugo/Cargo.toml, bpaf_cauwugo/README.md, bpaf_cauwugo/src/add.rs, bpaf_cauwugo/src/build.rs, bpaf_cauwugo/src/check.rs, bpaf_cauwugo/src/clean.rs, bpaf_cauwugo/src/lib.rs, bpaf_cauwugo/src/main.rs, bpaf_cauwugo/src/metadata.rs, bpaf_cauwugo/src/opts.rs, bpaf_cauwugo/src/run.rs, bpaf_cauwugo/src/shared.rs, bpaf_cauwugo/src/test.rs, src/args.rs, tests/completion.rs
limited commands for now but seem to work
=> cauwugo - dynamic shel completion infused cargo

bpaf_cauwugo/README.md, bpaf_cauwugo/src/add.rs, bpaf_cauwugo/src/lib.rs, src/meta_usage.rs, tests/meta_usage.rs
Mostly making the command line options closer to one of `cargo`'s
Fixes #91
=> Cauwugo add fixes

Cargo.toml, bpaf_derive/Cargo.toml, bpaf_derive/src/field.rs, bpaf_derive/src/lib.rs, bpaf_derive/src/top.rs, bpaf_derive/src/top_tests.rs, bpaf_derive/src/utils.rs, src/_applicative.rs, src/args.rs, src/from_os_str.rs, src/meta_help.rs, src/params.rs, tests/completion.rs, tests/tests.rs
- `bpaf_derive`: cleanup and change MSRV to 1.34.0
- minor optimizations
- applicative docs
=> applicative docs + misc changes

Cargo.toml, Changelog.md, README.md, bpaf_cauwugo/Cargo.toml, bpaf_cauwugo/src/shared.rs, bpaf_derive/src/top_tests.rs, src/_applicative.rs, src/lib.rs, tests/tests.rs
Mostly cosmetics and compatibility with strange things
=> Release 0.7.1

Changelog.md, src/arg.rs, src/tests.rs, tests/tests.rs
=> handle stranger things like -Obits=2048 without crashig

Cargo.toml, Changelog.md, bpaf_cauwugo/Cargo.toml, bpaf_derive/src/field.rs, bpaf_derive/src/field/named_field.rs, bpaf_derive/src/field_tests.rs, bpaf_derive/src/top.rs, examples/basic.rs, examples/derive_this_or_that.rs, examples/shared_args.rs, src/complete_gen.rs, src/complete_run.rs, src/complete_shell.rs, src/lib.rs, src/structs.rs, src/tests.rs, tests/completion.rs
Fixes https://github.com/pacak/bpaf/issues/109
=> Complete file

Cargo.toml, Changelog.md, README.md, bpaf_cauwugo/Cargo.toml, bpaf_derive/Cargo.toml, bpaf_derive/src/field/named_field.rs, bpaf_derive/src/field_tests.rs, src/complete_run.rs
=> Release 0.7.4

Cargo.toml, Changelog.md
- improve error messages when several conflicting options are specified
- improve category theory docs
- improve docs
=> Release 0.7.5

Cargo.toml, Changelog.md, src/complete_run.rs
seems like nightly ghc has changed something, trying to fix docs
=> release 0.7.6

Cargo.toml, Changelog.md, src/info.rs, src/item.rs, src/lib.rs, src/manpage.rs, src/meta_help.rs, src/params.rs, tests/manpage.rs
=> Release 0.7.7

src/manpage.rs
closes #140 
The subsection level is a bit over-used IMO, butnI dont know of a better structure either that respects both the "sub"- nature of sub-commands as well as their option-group labels.
(based on #138)
=> manpages: Add group labels

Changelog.md, bpaf_cauwugo/src/lib.rs, src/_flow.rs, src/batteries.rs, src/info.rs, src/lib.rs, src/manpage.rs, src/meta.rs, src/meta_help.rs, src/meta_usage.rs
- manpage generation bugfixes,
thanks to @ysndr
- internal cleanups
=> misc changes

Cargo.toml, Changelog.md, README.md, src/args.rs, src/complete_gen.rs, src/complete_shell.rs, src/structs.rs, tests/completion.rs
- manpage generation bugfixes,
- internal cleanups
- avoid impossible shell completions
Fixes #162
=> Release 0.7.8

examples/very_custom_usage.rs, src/meta_youmean.rs, src/structs.rs, tests/meta_youmean.rs
Fixes https://github.com/pacak/bpaf/issues/151
Fixes https://github.com/pacak/bpaf/issues/154
=> Various error messages improvements

Changelog.md, bpaf_derive/src/field/named_field.rs, bpaf_derive/src/field_tests.rs, bpaf_derive/src/top.rs, bpaf_derive/src/top_tests.rs, docs/src/anywhere_1/cases.txt, docs/src/anywhere_1/combine.rs, docs/src/anywhere_1/derive.rs, src/args.rs, src/docs/anywhere_1.md, src/lib.rs, src/meta_youmean.rs, src/structs.rs
Plus some documentation improvements
=> derive boxed and anywhere

bpaf_derive/src/field/named_field.rs, src/_derive_tutorial.rs
In response to feedback in https://github.com/pacak/bpaf/issues/178
=> Improve the docs/error messages

Changelog.md, bpaf_derive/src/field/named_field.rs, bpaf_derive/src/field_tests.rs, docs/src/many/cases.txt, docs/src/some/cases.txt, docs/src/some/combine.rs, docs/src/some/derive.rs, src/docs/many.md, src/docs/some.md, src/lib.rs, src/structs.rs, tests/tests.rs
=> make sure `env` works with combination of `many`

Changelog.md, bpaf_derive/src/field_tests.rs, bpaf_derive/src/top.rs, bpaf_derive/src/top_tests.rs, docs/src/anywhere_1/cases.txt, examples/dd.rs, examples/find.rs, examples/xorg.rs, src/args.rs, src/docs/anywhere_1.md, src/docs/dd.md, src/docs/find.md, src/docs/xorg.md, src/lib.rs, src/params.rs, src/structs.rs, tests/anywhere.rs
Fixes #171
@ysndr, can you take a look if this does what you want? If it is - I'll make a new release.
Todo:
=> Positional bool

bpaf_derive/src/top.rs, bpaf_derive/src/top_tests.rs, tests/derive.rs
Fixes https://github.com/pacak/bpaf/issues/163
=> bpaf_derive: derive command for singleton structs

src/params.rs, tests/tests.rs
Fixes https://github.com/pacak/bpaf/issues/173
=> Hidden env

src/structs.rs, tests/tests.rs
fixes https://github.com/pacak/bpaf/issues/153
=> anywhere can consume nothing

docs/src/adjacent_0/cases.txt, docs/src/adjacent_1/cases.txt, docs/src/boxed/combine.rs, docs/src/cargo_helper/cases.txt, docs/src/req_flag/cases.txt, src/args.rs, src/batteries.rs, src/docs/adjacent_0.md, src/docs/adjacent_1.md, src/docs/boxed.md, src/docs/cargo_helper.md, src/docs/req_flag.md, src/help.rs, src/info.rs, src/meta_help.rs, src/meta_youmean.rs, src/structs.rs, tests/adjacent.rs, tests/anywhere.rs, tests/errors.rs, tests/meta_youmean.rs, tests/tests.rs
Fixes #155 
Should be giving better error messages:
- less repetition on conflicting options
- point out at unexpected parts when requesting something expected
=> Better errors

bpaf_derive/src/top.rs, bpaf_derive/src/top_tests.rs, tests/help_format.rs
Fixes https://github.com/pacak/bpaf/issues/150
=> top level doc comments on a parser are now group_help

src/info.rs, src/item.rs, src/lib.rs, src/manpage.rs, src/meta_help.rs, src/params.rs, src/structs.rs, tests/help_format.rs
Fixes https://github.com/pacak/bpaf/issues/199
=> Display env fallback for flags too

src/structs.rs, tests/completion.rs
Fixes a problem described in https://github.com/pacak/bpaf/discussions/197
=> Bugfix: fallback/fallback_with should not interrupt the completion

Changelog.md, docs/src/anywhere/combine.rs, docs/src/anywhere_1/cases.txt, examples/find.rs, src/args.rs, src/docs/anywhere.md, src/docs/anywhere_1.md, src/docs/find.md, src/help.rs, src/meta_youmean.rs, src/structs.rs, tests/anywhere.rs, tests/meta_youmean.rs
This should improve error messages 
- inside anywhere blocks
- when positional interacts with non positional items
- extra tests :)
Fixes https://github.com/pacak/bpaf/issues/196
=> Better errros

bpaf_derive/src/attrs.rs, bpaf_derive/src/field_tests.rs, bpaf_derive/src/td.rs, bpaf_derive/src/top_tests.rs, bpaf_derive/src/utils.rs, src/buffer/html.rs
plus tests
Fixes https://github.com/pacak/bpaf/issues/223
=> take expressions and allow trailing commas in more places in bpaf_derive

Changelog.md, bpaf_derive/src/top_tests.rs, examples/customize_help.rs
=> update documentation and examples about '{usage}'

src/buffer.rs, src/info.rs, src/item.rs, src/meta.rs, src/meta_help.rs, src/meta_youmean.rs, src/params.rs, tests/help_format.rs
Fixes https://github.com/pacak/bpaf/issues/224
=> restore deduplication logic

Changelog.md, docs2/src/fallback_with/combine.rs, docs2/src/fallback_with/derive.rs, src/buffer.rs, src/docs2/fallback_with.md, src/info.rs, src/item.rs, src/lib.rs, src/meta.rs, src/meta_help.rs, src/meta_youmean.rs, src/params.rs, src/structs.rs, tests/help_format.rs
=> display_fallback and debug_fallback for parse_with

Cargo.toml, Changelog.md, bpaf_cauwugo/Cargo.toml, bpaf_derive/Cargo.toml, examples/basic.rs, examples/cargo-cmd.rs, examples/coreutils.rs, examples/csample.rs, examples/derive-smart-pointer.rs, examples/derive_commands.rs, examples/derive_rudo.rs, examples/derive_this_or_that.rs, examples/env_logger.rs, examples/many_comma_separated_args.rs, examples/many_comma_separated_args_derive.rs, examples/numeric_prefix.rs, examples/simple_dynamic.rs, examples/verbose.rs, examples/xorg.rs, src/args.rs, src/doc.rs, src/docs2/simple_dynamic.md, src/lib.rs, tests/tests.rs
Main change for 0.9.2 is a way to generate pure markdown user documentation for app's command line
=> Release 0.9.2

Changelog.md, bpaf_derive/src/attrs.rs, bpaf_derive/src/field_tests.rs, docs2/src/collect/cases.md, docs2/src/collect/combine.rs, docs2/src/collect/derive.rs, src/docs2/collect.md, src/lib.rs, src/structs.rs, tests/tests.rs
allows collecting multiple items into an arbitrary `FromIterator` collection
=> Parser::collect`

Cargo.toml, Changelog.md, README.md, bpaf_cauwugo/Cargo.toml
Mostly docs.rs documentation, but also `Parser::collect`
=> Prepare to release 0.9.3

Changelog.md, bpaf_derive/src/field_tests.rs, bpaf_derive/src/utils.rs
=> support raw identifiers in derive macro

src/buffer/html.rs, src/info.rs, tests/help_format.rs, tests/tests.rs
Fixes https://github.com/pacak/bpaf/issues/289
=> Make sure --version contains a newline at the end

src/lib.rs, src/params.rs
This should allow to unify ParseAny under single primitive parser type
Fixes #300 
Technically a breaking change, two type parameters on `ParseAny` are gone, but users are not supposed to name it.
=> Convert checker function inside ParseAny into a trait object

README.md
Like the title says, I hope they are good edits!
=> fix: typos in the README.md

docs2/src/cargo_helper/combine.rs, docs2/src/cargo_helper/derive.rs, src/docs2/cargo_helper.md
By commenting what "pretty" actually is.
I thought "pretty" is some special value 😅
=> doc: improve documentation of `cargo_helper`

Cargo.toml, Changelog.md, README.md, src/args.rs, src/buffer.rs, src/complete_gen.rs, src/error.rs, src/item.rs, src/lib.rs, src/meta.rs, src/meta_help.rs, src/structs.rs, tests/adjacent.rs, tests/anywhere.rs, tests/errors.rs, tests/tests.rs
- Improve error messages in case where parser that occurs earlier in a block fails (Fixes #350)
=> Release 0.9.11

Cargo.toml, Changelog.md, src/complete_run.rs, src/complete_shell.rs
- add license files (#388)
thanks @ davide
- fix fish completions - you'll need to regenerate completion files
Fixes #387
=> Release 0.9.14

Cargo.toml, Changelog.md, src/complete_run.rs
- a fix for a previous fix of fish completions, again - regenerate the files
=> Release 0.9.15

examples/derive.rs
…latest research
From the The Very Important Problems dept.
=> Update derive.rs: you should accept one as positive according to the latest research

bpaf_core/src/split.rs
Here an initial attempt, not using windows I do not have a good way to test it though...
=> Complete split_param for non-utf8

Cargo.toml, Changelog.md, src/lib.rs, src/params.rs, src/structs.rs
- Documentation fixes (#424)
thanks @yuriks
- A few clippy suggested fixes
=> Release 0.9.20
