pacak/bpaf

- README.md
- bpaf_derive/src/field.rs
- bpaf_derive/src/top.rs
- examples/derive_show_asm.rs
- examples/negative.rs
- examples/positional.rs
- examples/positional_derive.rs
- examples/simple.rs
- src/args.rs
- src/info.rs
I'm still using and older rustc which does not support this new `format` syntax. This MR replaces the usages of that syntax to the traditional format with arguments.
It's called partial support because tests don't build because of some derive macro incompatability. The offending test is `help_with_default_parse`, and if I remove it all tests pass.
> Partial compatability with rustc 1.56

- docs/src/adjacent_0/cases.txt
- docs/src/adjacent_1/cases.txt
- src/docs/adjacent_0.md
- src/docs/adjacent_1.md
- src/structs.rs
- tests/adjacent.rs
Fixes https://github.com/pacak/bpaf/issues/80
> parse_option should retain Missing if it manages to consume something

- src/lib.rs
- src/structs.rs
- tests/tests.rs
* Adds a `pure_with` parser to be the lazily computed, fallible equivalent to `pure`
* Resolves #79
> Provide `pure_with` parser

- Changelog.md
- docs/src/argument/combine.rs
- docs/src/argument/derive.rs
- docs/src/positional/cases.txt
- docs/src/positional/combine.rs
- docs/src/positional/derive.rs
- examples/enum_in_args.rs
- src/_applicative.rs
- src/_derive_tutorial.rs
- src/docs/argument.md
- src/docs/positional.md
- src/from_os_str.rs
- src/item.rs
- src/lib.rs
- src/meta_help.rs
- src/meta_youmean.rs
- src/params.rs
- tests/meta_youmean.rs
> Drop FromOsStr trait

- Cargo.toml
- Changelog.md
- README.md
- bpaf_derive/src/field.rs
- bpaf_derive/src/field/named_field.rs
- bpaf_derive/src/field_tests.rs
- src/_applicative.rs
- src/args.rs
- src/lib.rs
- src/params.rs
- src/structs.rs
- tests/pure_with.rs
Other than `FromOsStr` change - it's a minor release.
- `pure_with` implementation
thanks to @xitep
- `FromOsStr` is replaced with magical uses of `Any` trait
- `hide_usage`
- `bright-color` and `dull-color` features
- accept fully qualified names in more places in `bpaf_derive`
- cosmetic improvements
- documentation improvements
1. Remove FromUtf8 annotations if you have any
```diff
-let coin = short('c').argument::<FromUtf8<Coin>>("COIN");
+let coin = short('c').argument::<Coin>("COIN");
```
In many cases rustc should be able to derive what the type
2. Replace `FromOsStr` implementations for your types with `FromStr`
if you have any. If your type requires parsing `OsString` directly
you can perform it in two steps - consuming `OsString` + parsing it
with `Parser::parse`
3. If you want …
> release 0.7.0

- src/color.rs
While I don't have much experience with `owo_colors`, I tried playing around with the colors and got results that match cargo more closely in my ubuntu terminal:
[cargo](https://i.imgur.com/ncIiatA.png)
[before](https://i.imgur.com/B0qOM3h.png)
[after](https://i.imgur.com/13KSQGK.png)
It could be that it's just the bold that making it look more like a closer match
> Update colors to match cargo's more closely

- src/lib.rs
- src/meta_usage.rs
Removed a couple remaining references to `argument_os`. Additionally, I uncommented `number_5` in the example in the [Derive specific considerations](https://docs.rs/bpaf/0.7.1/bpaf/trait.Parser.html#derive-specific-considerations) section in the docs for `Parser` because it does compile now.
> Remove old references to argument_os

- Cargo.toml
- Changelog.md
- README.md
- bpaf_cauwugo/Cargo.toml
- docs/src/guard/cases.txt
- docs/src/req_flag/cases.txt
- src/args.rs
- src/docs/guard.md
- src/docs/req_flag.md
- src/info.rs
- src/meta_youmean.rs
- src/structs.rs
- tests/errors.rs
- tests/tests.rs
- drop tainting logic, should be redundant
- improve error messages for guard and conflicting branches
> Release 0.7.2

- src/info.rs
Currently interactive parsing and error recovery is not possible at the same time is not possible.
`try_run` addresses that.
> Add `try_run` method

- src/manpage.rs
- tests/manpage.rs
The `AND` parser is currently a `todo!()`, i've added space separation to be able to print multiple command arguments.
> fix: print multiple arguments

- src/complete_run.rs
reset the compadd argument list for every command
> fix: show zsh description

- src/complete_run.rs
So there might be something I'm getting very wrong here:
I have a subcommand which passes through to a separate program with its own completer for bash and zsh.
the only way to get this working with bash was by the means of `source PATH_TO_COMPLETER; _subcommand_bash_completion`, because the completion adapter just executes this as an `eval`:
```rust
fn complete_subcommand_shell() -> bpaf::ShellComp {
bpaf::ShellComp::Raw {
bash: Box::leak(
format!(
"source {}; _subcommand_bash_completion",
env!("subcommand_BASH_COMPLETION_SCRIPT")
)
.into_boxed_str(),
),
zsh: ""
fish: "",
elvish: "",
}
}
```
trying to do the same with zsh however fails with
```
_myprogram:33: no such file or directory: source <PATH_TO_COMPLETER..>; _subcommand
```
unless i add an eval at the same position we have it in …
> Evaluate zsh shell complete function if given

- Cargo.toml
- Changelog.md
- bpaf_derive/Cargo.toml
- bpaf_derive/src/top.rs
- bpaf_derive/src/top_tests.rs
- examples/very_custom_usage.rs
- src/batteries.rs
- src/info.rs
- src/lib.rs
- a way to override `usage` in derive macro
- `ParseFailure::exit_code`
> Release 0.7.9 

- Cargo.toml
- Changelog.md
- bpaf_derive/Cargo.toml
- bpaf_derive/src/field.rs
- bpaf_derive/src/field/named_field.rs
- bpaf_derive/src/top.rs
- bpaf_derive/src/utils.rs
- src/args.rs
- src/buffer.rs
- src/color.rs
- src/complete_gen.rs
- src/help.rs
- src/info.rs
- src/item.rs
- src/lib.rs
- src/manpage.rs
- src/meta.rs
- src/meta_help.rs
- src/meta_usage.rs
- src/meta_youmean.rs
- src/no_color.rs
- src/params.rs
- src/structs.rs
- tests/derive.rs
- tests/help_format.rs
- tests/positionals.rs
- tests/tests.rs
- better error messages
- allow to (explicitly) derive positional bool
- better help messages for multiarg arguments
- syn 2.0
- derive for `anywhere` and `boxed`
> Release 0.7.10

- .github/workflows/check-and-lint.yaml
- Cargo.toml
- Changelog.md
- README.md
- bpaf_cauwugo/Cargo.toml
- bpaf_derive/Cargo.toml
- src/_unusual.rs
- src/batteries.rs
- src/lib.rs
- src/meta_help.rs
- src/params.rs
- src/structs.rs
- `any` now takes a function that checks if it matches the input or not.
You can still apply usual filtering with `guard`, etc after it but initial
filtering inside a function leads to better error messages.
- `anywhere` is now a method on `any` instead of being a parser method
and should now be used to make an arbitrary looking flag like parsers.
You can still parse blocks from arbitrary places using remaining `adjacent`
method
- `many` and `some` will now collect one result from a parser
that does not consume anything from an argument list allowing
for easier composition with parsers that consume from both
command line and environment variables. If your code depends on
the original behavior you should replace non failing parsers under
`many` with failing parsers: `req_flag` instead of …
> Release bpaf 0.8.0 and bpaf_derive 0.4.0

- src/args.rs
- src/params.rs
- src/structs.rs
- tests/errors.rs
Pick the first mismatch in case of mutually exclusive branches instead of first parsed element.
> Improve error messages a bit more

- Cargo.toml
- Changelog.md
- bpaf_derive/Cargo.toml
- examples/basic.rs
- src/args.rs
- src/info.rs
Mostly regression fixes, but you can now use `fallback_to_usage` if you want to print the usage when user specifies no arguments
```rust
options().fallback_to_usage().run()
```
> Prepare to release 0.9.1

- .gitignore
- src/buffer/html.rs
- tests/markdown.md
- tests/markdown.rs
I noticed that now the documentation can be emitted in HTML, so I thought also to have a markdown format.
The code is mostly a copy-paste of the render of the HTML, but I'm happy to refactor it with some direction. Ideally, we could move it to a `markdown.rs` file.
Leaving it as a draft at the moment, asking the following questions:
- I couldn't find a proper way to test the doc gen, so I just copied the manpage test for a POC
- the environment variable is rendered strangely, probably because it has different metadata; how do you suggest tackling this part?
- what kind of test cases would you like to add?
> feat: markdown rendering

- src/buffer/html.rs
- tests/markdown.rs
Currently, the markdown generated emits `# Header`, level one.
When the markdown is rendered to HTML, it creates `<h1>` tags, which are incorrect from the SEO point of view. Only one `h1` should be present in a page.
PR emits a `h1`  only for the app name and `h2` for the rest.
> fix: emit a level 2 heading for sub commands in markdown

- Changelog.md
- src/args.rs
- tests/errors.rs
- tests/params.rs
support squashing short flags as well as short arguments with their bodies inside the same flag.
Fixes #267
> Fancier short squashing

- bpaf_derive/src/top.rs
- bpaf_derive/src/top_tests.rs
- tests/params.rs
> bpaf_derive: fix command aliases for enum members

- Cargo.toml
- Changelog.md
- bpaf_derive/Cargo.toml
- fancier squashing: parse `-abfoo` as `-a -b=foo` if b is a short argument (#267)
- `bpaf_derive`: make sure command aliases are actually working (#278)
> Release 0.9.5 + 0.5.5 derive

- Changelog.md
- src/complete_gen.rs
- src/item.rs
- src/params.rs
- tests/tests.rs
Removes one of the `unreachable!()` branches that became reachable after I added `env` only parsers. Parse, don't validate yet again...
> Make sure hidden env-only flags, switches and arguments work

- Changelog.md
- src/args.rs
- src/docs2/adjacent_struct_0.md
- src/docs2/compose_basic_to_options.md
- src/docs2/custom_help_version.md
- src/docs2/derive_basic_custom_consumer.md
- src/docs2/to_options.md
- src/params.rs
- tests/errors.rs
`positional` should be used either after all the named items or as an item adjacent to a named item in some way, still after all the named items within the scope.
In case of valid user input scanning for or picking up the front item gives the same results. When user specifies an invalid item - it will not be consumed during normal scanning so picking the front item fails.
Error from positional item failing with "not present" will take the priority over "not expected" from invalid item resulting in a bad errormessage.
> Scan for positional items instead of trying to take the next available

- src/lib.rs
- src/params.rs
complains about env being a function and a macro feels like a bug - there is no `NamedArg::env!()`...
> cleanup warnings from a recent Rust release

- src/complete_shell.rs
The completion settings output by this library contains a syntax error. This was originally reported in https://github.com/akinomyoga/ble.sh/issues/368 for the completion setting for the `chezmoi_modify_manager` command.
> Fix syntax error in Bash completion

- Cargo.toml
- Changelog.md
- bpaf_derive/Cargo.toml
- docs2/src/choice/cases.md
- docs2/src/choice/combine.rs
- src/complete_gen.rs
- src/docs2/choice.md
- src/lib.rs
- src/meta_youmean.rs
- tests/errors.rs
- make sure env-only arguments and flags are working
- support raw identifiers in derive macro (#282)
- better error messages for a few corner cases
- bugfix in completions generator for bash (#311)
- `choice` combinator to efficiently construct alternative parsers at runtime (#308)
- use `eprintln!` + `std::process::exit` instead of panic if shell completions must be regenerated for less jarring user experience.
> Release 0.9.6

- .github/workflows/check-and-lint.yaml
- Cargo.toml
- src/lib.rs
From [reddit](https://www.reddit.com/r/rust/comments/184ijwg/ripgrep_14_released_hyperlink_support_regex/kaw5kz7/):
>  While I don't use lexopt I have been looking for a way to automatically generate a man page for a while (with bpaf in my case for one project, xflags for another project).
I was confused by this because manpages have been referenced before.  Looking on docs.rs, I just see
The link doesn't resolve to anything.
With this set of changes, it will now resolved to
Notes:
- As a contributor, knowing the exact set of features to enable was frustrating, so I copied the pattern from `clap` of having a feature for this.  I prefaced it with `unstable-` to communicate that there are no compatibility guarantees.  There are RFCs for improving this situation.
- I put the nightly feature …
> docs: Include documentation for manpages

- Cargo.toml
- Changelog.md
- bpaf_derive/Cargo.toml
- bpaf_derive/src/attrs.rs
- bpaf_derive/src/field_tests.rs
- bpaf_derive/src/help.rs
- bpaf_derive/src/named_field.rs
- bpaf_derive/src/td.rs
- bpaf_derive/src/top.rs
- bpaf_derive/src/top_tests.rs
- updated documentation a bit
- support for `#[bpaf(ignore_rustdoc)]`
- support for `descr`, `header`, `footer` and `help` top level annotation for `command` and `options`
Now you can tell `bpaf` to ignore rust doc comments
```rust
#[derive(Debug, Clone, Bpaf)]
/// This gets ignored
#[bpaf(options, ignore_rustdoc)]
struct Options {
#[bpaf(ignore_rustdoc, help("use this help instead")]
/// help  // <- this gets ignored
foo: String
}
```
```rust
/// those are options // <- this gets ignored in favor of explicit descr
#[bpaf(command, descr("descr"), header("header"), footer("footer"), help("help"))]
struct Opt;
```
> Release 0.9.7

- Changelog.md
- src/error.rs
Mentioned in https://github.com/pacak/bpaf/issues/325
> error: separate app name and supports with a space

- Cargo.toml
- Changelog.md
- legacy/Cargo.toml
This drops the dependency for is-terminal in favor of implementation that comes in stdlib
> Stop supporting colored output for legacy rustc

- bpaf_derive/src/td.rs
- bpaf_derive/src/top.rs
- src/buffer.rs
- src/buffer/console.rs
- src/error.rs
- src/info.rs
- tests/errors.rs
- tests/meta_youmean.rs
- tests/tests.rs
`bpaf` currently applies column wrapping at a hardcoded width of [100](https://github.com/pacak/bpaf/blob/a86daeca198254d1beae6a37c8c012e1df160c11/src/buffer/console.rs#L42) characters.
This PR aims to make this width configurable via the option parser.
Additionally it contributes a fix to the breaking logic where earlier only the current cursor position was used to determine, resulting in the trailing word overflowing the set width of 100.
> make `max_width` of help configurable

- bpaf_derive/Cargo.toml
- bpaf_derive/src/attrs.rs
- bpaf_derive/src/custom_path.rs
- bpaf_derive/src/help.rs
- bpaf_derive/src/lib.rs
- bpaf_derive/src/named_field.rs
- bpaf_derive/src/td.rs
- bpaf_derive/src/top.rs
- bpaf_derive/src/top_tests.rs
- bpaf_derive/src/utils.rs
Suppose that we have a crate called `indirector`. 
`indirector` publicly re-exports `bpaf`:
```rust
pub use bpaf;
pub use bpaf::Bpaf;
```
Then, we have a crate called `user`, which imports `indirector`, and uses `bpaf` through it:
```rust
use indirector::bpaf::{Parser, Bpaf};
```
This will cause a hygiene related issue, because currently `bpaf_derive` assumes that `bpaf` is available globally (via `::bpaf`) [in line with the official recommendations](https://doc.rust-lang.org/reference/procedural-macros.html#procedural-macro-hygiene).
There was a [discussion](https://users.rust-lang.org/t/how-to-express-crate-path-in-procedural-macros/91274/1) on how to address this sort of issue, which lead me to [experiment](https://github.com/bzm3r/hygiene_mnwe) with the [two …
> bpaf_derive: allow specification of a custom crate path to resolve proc_macro hygiene related issues that might develop in some situations

- bpaf_derive/src/attrs.rs
- bpaf_derive/src/field_tests.rs
I got curious, and wanted to add support for `anywhere` for derive after https://github.com/pacak/bpaf/discussions/347.
Overall I just grepped for keywords to know where I needed to add it. So feel free to nit, if you want any changes.
Additionally, I tested that it works locally, but I didn't add any tests to assert it. I'll happily add some tests, just mention where you prefer I add them.
> Added anywhere support for derive

- Cargo.toml
- Changelog.md
- bpaf_derive/Cargo.toml
- src/args.rs
- src/complete_gen.rs
- src/complete_run.rs
- src/complete_shell.rs
- src/docs2/choice.md
- src/error.rs
- tests/errors.rs
- Added `OptionParser::max_width` and `#[bpaf(max_width(xxx))]` to specify maximum
width of help output
- Added a custom path attribute to allow using of reexported bpaf
thanks @bzm3r
- support anywhere in bpaf_derive
thanks @vallentin
- small documentation improvements
thanks @Boshen
- minor shell completion improvements
- avoid panic in case of hidden but required parser argument (#345)
> Release 0.9.10

- src/buffer.rs
A follow up to #340 allowing `format!("{doc:80}")` t0 print a doc at a defined width.
> Allow `Doc` to `Display` impl to use defined width

- Cargo.toml
- Changelog.md
- src/error.rs
- tests/errors.rs
Improve error messages for a scenario where a flag that can be used just once is used twice or more and the whole parser contains a similarly looking flag
> Release 0.9.12

- src/complete_shell.rs
When debugging issue #371 , I noticed the `Raw` shell completion mode was pretty much unusable due to adding extra quotes around the input, causing zsh and bash to interpret the entire raw input as a single command, which would always fail due to not found. Currently it is only possible to use a single command with no args in raw mode. I also noticed an extra set of quotes are being added to file and dirs for bash, already handled by the `Shell` wrapper, which could be causing issues.
- Removed quotes around bash and zsh raw completions, allowing freedom to use arguments/multiple commands in the raw completions
- Removed duplicate quotes around bash file and dir completions, seems like the `Shell` wrapper already handles this and they weren't updated
> fix(complete shell): remove quotes for zsh/bash raw, remove duplicated quotes in bash file and dir 

- examples/filenames.rs
- src/complete_shell.rs
- src/lib.rs
Support masks with multiple extensions via `"*.(md|toml)"`
`zsh` accepts `"*.(md|toml)"`, but bash wants to see `"@(md|toml)"`. To support both we pick saner mask variant (from `zsh`) and in case of `bash` - correct it.
Fixes #371
> Support more masks with multiple extensionss in ShellComp::File

- src/params.rs
- tests/completion.rs
- copy is good when cheap
- exhaustive pattern match is good
- and we should be careful about suggesting completions - `--` doesn't fit there
> Test and a small refactor for non-strict positional

- src/args.rs
- src/complete_gen.rs
- src/complete_shell.rs
- src/structs.rs
- tests/chezmoi.rs
- tests/completion.rs
Extracted from #337
- track shell completions origin - named or positional and use similar to other completions
- when combining completions from two branches - use both or use one that captured earlier value
> Completion: move careful handling of mix of positional and non-positional items

- src/info.rs
- tests/completion.rs
- don't demand for disambiguation during completion process 
- additional tests
> Autocomplete improvements

- Cargo.toml
- Changelog.md
- bpaf_derive/Cargo.toml
- src/error.rs
- src/info.rs
- You can now use `fallback_to_usage` in derive macro for options and subcommands (#376)
- Bugfixes related to shell completion and file masks
thanks @ozwaldorf
- `not_strict` restriction for positional items (TODO - check the docs)
thanks @ozwaldorf
- more shell completion bugfixes (#384, #382, #381)
- `ParseFailure::print_mesage` (with one `s` is deprecated in favor of the right spelling
> Release 0.9.13

- Cargo.toml
- LICENSE-APACHE
- LICENSE-MIT
- bpaf_cauwugo/LICENSE-APACHE
- bpaf_cauwugo/LICENSE-MIT
- bpaf_derive/LICENSE-APACHE
- bpaf_derive/LICENSE-MIT
The crates in this repository are licensed under MIT OR Apache-2.0 according to the cargo metadata, but don't actually include the license texts, which is technically a requirement for MIT. This PR adds the license texts to the repo and ensures they'll be included in all packaged crates.
> Add license texts

- Cargo.toml
- Changelog.md
- bpaf_derive/Cargo.toml
- bpaf_derive/src/field_tests.rs
- bpaf_derive/src/named_field.rs
- examples/env_logger.rs
- tests/derive.rs
- treat `pure` as an implicit consumer - don't add unnecessary `.optional()` or `.many()`
- unbrainfart one of the examples
> Release 0.9.16

- Cargo.toml
- Changelog.md
- bpaf_derive/Cargo.toml
- A new method `format_fallback` allows to format fallback values using
a custom formatting function. This extends functionality offered by `format_debug` and
`format_display` that use `Debug` and `Display` instances respectively
thanks @antalsz
> Release 0.9.17

- src/info.rs
fallback_to_usage should apply if parser fails to produce a result.
> Make fallback_to_usage behavior more expected

- Cargo.toml
- Changelog.md
- src/info.rs
- tests/help_format.rs
Fix one more problematic corner case of `fallback_to_usage`. It should not override inner parser printing usage or version info:
If parser supports subcommand "foo" then passing "app foo --help" should return help for "foo", not for the app itself
> Release 0.9.19

- docs2/Cargo.toml
- docs2/build.rs
- docs2/src/custom_usage/combine.rs
- docs2/src/custom_usage/derive.rs
- docs2/src/lib.rs
- src/docs2/custom_usage.md
The Derive example was under the "Combinatoric" section and vice-versa.
> Fix order/label of examples in custom_usage.md
